name: Run integration tests from app -> proxy -> dicom server
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Set up Minikube
      run: |
        export SHELL=/bin/bash
        curl -JLO "https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64"
        echo '6d31c65b03972c6dc4a14ab429f2928300518b26503f58723e532d1b0a3bbb52  mkcert-v1.4.4-linux-amd64' | sha256sum -c
        chmod +x mkcert-v*-linux-amd64
        sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
        mkcert -key-file key.pem  -cert-file cert.pem "*.imaging-local.argo.run" "imaging-local.argo.run"
        echo $(minikube ip)    imaging-local.argo.run | sudo tee -a /etc/hosts
        echo $(minikube ip)    launcher.imaging-local.argo.run | sudo tee -a /etc/hosts
        kubectl -n kube-system create secret tls mkcert \
            --key key.pem \
            --cert cert.pem
        echo "kube-system/mkcert" | minikube addons configure ingress
        minikube addons enable ingress
    - name: Build Images
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker pull ghcr.io/jmandel/smart-launcher-v2:latest
        docker tag ghcr.io/jmandel/smart-launcher-v2:latest argonautcontainerregistry.azurecr.io/smartonfhir/smart-launcher-2:latest
        cd viewer
        npm ci
        npm run build --  --base=/app
        mv dist ../server/public
        cd ../server
        docker build -t argonautcontainerregistry.azurecr.io/imaging-proxy:latest .
        echo -n "verifying images:"
        docker images
    - name: Launch Minikube Stack
      run: |
        export SHELL=/bin/bash
        cd server
        kubectl apply -f k8s/base.yml -f k8s/minikube.yml
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install playwright
      working-directory: ./integration
      run: |
        npm ci
        npx playwright install chromium --with-deps
    - name: Wait for sample data then run playwright
      working-directory: ./integration
      run: |
        while true; do
          echo "------- Starting new check iteration -------"
          echo "Timestamp: $(date)"
          
          # Make the find query and store response
          echo "Making find query..."
          FIND_RESPONSE=$(curl -s -k https://argonaut:argonaut@imaging-local.argo.run/orthanc/tools/find -d '{"Level":"Study","Query":{"PatientName":"Kshlerin*"}}')
          LINE_COUNT=$(echo "$FIND_RESPONSE" | wc -l)
          BYTE_COUNT=$(echo "$FIND_RESPONSE" | wc -c)
          
          echo "Response line count: $LINE_COUNT lines"
          echo "Response byte count: $BYTE_COUNT bytes"
          echo "Raw response:"
          echo "$FIND_RESPONSE" | jq '.' || echo "$FIND_RESPONSE"
          
          if [ "$LINE_COUNT" -ge "20" ]; then
            echo "Success! Found $LINE_COUNT lines (>= 20 lines). Exiting loop."
            break
          fi
          
          # Debug information for failed iteration
          echo "Checking studies endpoint..."
          curl -k -v https://argonaut:argonaut@imaging-local.argo.run/orthanc/studies 2>&1
          
          echo "Current pods status:"
          kubectl -n smart-imaging-access get pods
          
          echo "Orthanc logs:"
          kubectl -n smart-imaging-access logs deployments/orthanc --tail=20
          
          echo "Reference logs:"
          kubectl -n smart-imaging-access logs deployments/reference --tail=20
          
          echo "Sample-loader logs:"
          kubectl -n smart-imaging-access logs deployments/reference -c sample-loader --tail=20
          
          echo "Waiting 10 seconds before next attempt..."
          sleep 10
        done

        echo "Loop completed successfully. Proceeding with playwright tests..."
        npx playwright test

